### ISSUE TITLE
Hello from `check_please`!

### ISSUE THREAD

**Issue by geeksam** [splitwise/super_diff#102]
Hi!  This isn't actually an issue per se; I just wanted to say hello.  :)

I saw this library mentioned in Ruby Weekly the other day.  I've recently started working on a project called [check_please](https://github.com/RealGeeks/check_please) that has a fair bit of overlap with this one.

For context:  I've been working on replacing a janky HTTP API written in Python _(to be clear, this is not a dig on Python—it would've been just as janky had it been written in Ruby!)_ one API endpoint at a time.  `check_please` started life as a custom RSpec matcher, but I got tired of copy/pasting JSON into a file and then loading that file in the specs... so I wrote a CLI that lets me `pbpaste` the `actual` output, and now I think of it as mostly a command-line utility that also happens to have an RSpec matcher (in a separate gem).

Here are the main diffs (heh) as I see them:

* I love that `super_diff` has an architecture that supports registering custom diffing classes.  In contrast, since `check_please` was born as a way of comparing two JSON docs, it assumes you're only dealing with core classes that can survive a JSON-serialization round trip.
* Because the two documents might have a large number of diffs, `check_please` aims for more compact output, especially with respect to vertical whitespace:
  * It produces summarized tabular output (via the `table_print` gem) by default.
  * When it reaches a node in the tree where one document has a collection (read: Array or Hash) and the other does not, it simply declares a "type mismatch" and refuses to descend further.
  * I've added a "max depth" option and a couple of `grep`-like options for filtering output based on a very simple path syntax, in case the user wants to focus on a specific aspect of the comparison rather than attempting to "eat the elephant" in one go.  _[EDIT: the filtering options only exist in a local branch that I'll probably throw away and attempt again after some rearchitecture]_

Because I started with a somewhat different focus, I don't think it currently makes sense to combine these two projects... but I figured I'd at least say hello, and I've linked to your project from mine.  Please feel free to steal as many of my ideas as you like, and I'll try to make some time to read through your code this week.  :)

Happy hacking!
-Sam

**Comment by mcmire** [comment]
Hello there, nice to meet you! It's nice to hear from someone who's felt the same pain with regard to comparing data. Compared to working with complexity around reshaping how RSpec handles diffing, it was a refreshing experience looking at your solution 😆 It's very straightforward and easy to understand. Also I didn't know about `table_print` — that seems very handy for scripts and such. Anyway, I appreciate the linkback, and I'll be keeping an eye on your gem for future updates!
