### ISSUE TITLE
Missing GitHub Release for 0.5.2

### ISSUE THREAD

**Issue by nilbus** [splitwise/super_diff#103]
I see [0.5.2 is released on RubyGems][release], but there's no corresponding tag/release on the GitHub repository here. Mind adding that in? Otherwise, it looks like the project hasn't been updated in a year and a half.

![image](https://user-images.githubusercontent.com/64751/99979296-f08a8c00-2d74-11eb-8406-5f8f439059f5.png)

Thanks! 😄 

[release]: https://rubygems.org/gems/super_diff

**Comment by mcmire** [comment]
Yeah, sorry. I need to figure out a way to synchronize the CHANGELOG with the Releases page. That should be fixed now.

**Comment by nilbus** [comment]
Thanks!
