### ISSUE TITLE
super_diff does not work correctly in rspec matcher

### ISSUE THREAD

**Issue by centralhardware** [splitwise/super_diff#105]
code: 

```ruby
RSpec::Matchers.define :matcher do |expected|
  match do |actual|
    expect(actual).to match(expected)
  end

  failure_message do |actual|
   
    end
  end
  diffable
end
```
in result^ 

don't show expected and to_mach

show 

![image](https://user-images.githubusercontent.com/26829359/100057264-afb87300-2e59-11eb-9620-26ece6d60f9b.png)

show content of expected but without difference beetwin actual and expected

**Comment by mcmire** [comment]
Thanks for the report! I'll take a look at what's going on here.

**Comment by mcmire** [comment]
@centralhardware I'm revisiting this, and actually, would you mind giving a more complete example? For instance, what is your `expected` and `actual` in this scenario? Otherwise I'm not sure what would be causing this.

**Comment by mcmire** [comment]
I'm going to close this as I need some more information to look into this further, but feel free to respond and I will reopen this!
