### ISSUE TITLE
Add license to gemspec

### ISSUE THREAD

**Issue by hlascelles** [splitwise/super_diff#109]
This gemspec could do with a license so it doesn't show as a failure with tools like [license_finder](https://github.com/pivotal/LicenseFinder).

I think it is MIT?

**Comment by mcmire** [comment]
Yup, it's MIT. See https://github.com/mcmire/super_diff/blob/master/LICENSE.

Can you tell me more about what you're trying to do? How are you using `license_finder`?

**Comment by hlascelles** [comment]
Yep, sure... There is a field in the gemspec specification that allows a gem to declare its license programmatically. See the details [here](https://guides.rubygems.org/specification-reference/#licenseo). The specification says it "should" be present.

The gem license_finder is one of the apps that requires it to be there to tell the license of a project. See [here](https://github.com/pivotal/LicenseFinder#a-plea-to-package-authors-and-maintainers) for their description of how/why/where they expect that line.

So if you're open to it, I could make a PR that will add that line (it will literally be a one-liner)?

**Comment by mcmire** [comment]
Okay, that's fine with me!

**Comment by hlascelles** [comment]
Opened PR :+1:
