### ISSUE TITLE
Ruby 3.0 support?

### ISSUE THREAD

**Issue by joshRpowell** [splitwise/super_diff#117]
@mcmire thanks for such a great tool. thoughts on Ruby 3 support?

**Comment by mcmire** [comment]
@joshRpowell Yes, I think that makes sense! The good thing is that now that tests are being run on GitHub Actions, it should be pretty easy to [add a new version to the action file](https://github.com/mcmire/super_diff/blob/master/.github/workflows/super_diff.yml#L11) and start testing on Ruby 3 and see what breaks. Curious to know how many other gems are compatible with Ruby 3 yet. Feel free to submit a PR if you like, or I'll take a look at this relatively soon.

**Comment by mcmire** [comment]
Starting with 0.6.0 you should now be able to use the gem with Ruby 3.0. Cheers!
