### ISSUE TITLE
SuperDiff::ObjectInspection.inspect violates Liskov Substitution Principle

### ISSUE THREAD

**Issue by dgutov** [splitwise/super_diff#119]
Breaking certain kinds of introspection:

```rb
> SuperDiff::ObjectInspection.method(:inspect).owner.to_s
ArgumentError: wrong number of arguments (given 0, expected 1; required keyword: as_single_line)
from /home/dgutov/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/super_diff-0.4.2/lib/super_diff/object_inspection.rb:13:in `inspect'
```

**Comment by dgutov** [comment]
Could you rename that method to `call`, `perform` or etc?

**Comment by mcmire** [comment]
Ah... yeah, that would break stuff, wouldn't it. I forgot that classes can be inspected too. Thanks for letting me know about this, I'll add a fix for this soon.

**Comment by mcmire** [comment]
Closing since this should be fixed now!
