### ISSUE TITLE
match_array + hash_including raises exception

### ISSUE THREAD

**Issue by dbackeus** [splitwise/super_diff#132]
Eg.
```ruby
  it "fails with super_diff" do
    expect([{"message" => "lol"}]).to match_array(
      hash_including("message" => "lol")
    )
  end
```

Results in:
```
NoMethodError:
  undefined method `size' for #<RSpec::Mocks::ArgumentMatchers::HashIncludingMatcher:0x00007fd42da5e3e0>
```

Commenting out `require "super_diff/rspec-rails"` in my spec helper fixes the issue.

**Comment by nickstanish** [comment]
I found a workaround: add an array instead of using varargs

```ruby
    expect([{"message" => "lol"}]).to match_array([
      hash_including("message" => "lol")
    ])
```

**Comment by djsmentya** [comment]
Hi @mcmire

Any reasons suggested PR by @wata727  was not merged?  It looks like quite a valuable fix.

**Comment by afuno** [comment]
Hi @mcmire 

Is there a rough estimate for fixing this issue?

**Comment by dbackeus** [comment]
This issue was closed via https://github.com/mcmire/super_diff/pull/213
