### ISSUE TITLE
Must require 'super_diff/version' to access SuperDiff::VERSION

### ISSUE THREAD

**Issue by ransombriggs** [splitwise/super_diff#145]
I tried to load `SuperDiff::VERSION` but it appears to not be auto-loaded and had to require manually.

**Comment by mcmire** [comment]
Yeah, it's not something I or anyone else has ever needed to access outside the gemspec, so this request hasn't come up yet, but if you think people would expect it to be accessible in general then I'm happy to merge a PR!

**Comment by ransombriggs** [comment]
I was going to monkey patch around https://github.com/mcmire/super_diff/issues/144 and leave a note to check if we could remove the monkey patch if the version updated beyond `0.8.0` and that was fixed, went ahead and pushed up a PR: https://github.com/mcmire/super_diff/pull/147

**Comment by mcmire** [comment]
This was closed by #147.
