### ISSUE TITLE
Breaks RSpec extra failure lines support

### ISSUE THREAD

**Issue by palkan** [splitwise/super_diff#157]
RSpec [metadata[:extra_failure_lines]](https://github.com/rspec/rspec-core/pull/2092) are not honored by super_diff.

This mechanism is used by rspec-rails system tests integration to display the link to a failure screenshot. With super_diff, we don't have this information in output.

**Comment by mcmire** [comment]
Ah. [`super_diff` patches RSpec across the board](https://github.com/mcmire/super_diff/blob/24a9b10648a218632cc7942fc5709112b48dad68/lib/super_diff/rspec/monkey_patches.rb) to color different parts of the output, including ExceptionPresenter, and looking at the code again, I don't think this functionality is being included. This should be a fairly easy one to integrate. I can look into this when I get a chance, although a PR would certainly be welcome.

**Comment by mcmire** [comment]
I was looking through the issues list and noticed that this issue is already filed as #108. So I'm going to close this as a duplicate but keep the other one open for tracking.
