### ISSUE TITLE
Option to disable the key (legend)

### ISSUE THREAD

**Issue by tradiff** [splitwise/super_diff#165]
Love the gem! Is there a way to disable the key? It becomes noise after a while once the user has learned the colors and symbols.  If there is not currently a way to do this, would you be open to a PR to add this configuration?

**Comment by mcmire** [comment]
There is not currently a way to disable the key, but yes, I would be open to a PR!

**Comment by tradiff** [comment]
@mcmire I have the feature added, but I'm not sure where I should add specs for the new behavior. Do you have any suggestions on that? [Here's my branch](https://github.com/mcmire/super_diff/compare/master...travatomic:super_diff:disable-key?diff=split) if you're interested in a sneak peek.
