### ISSUE TITLE
controller test broken: eval error: undefined method `keys' for nil:NilClass

### ISSUE THREAD

**Issue by fwolfst** [splitwise/super_diff#199]
We have a pretty straight forward controller test that breaks execution

```ruby
   context 'with the user not logged in' do
      context 'when the operation name contains "private"' do
         it 'returns a 403' do
           post :execute, as: :json, params: { query:, operationName: 'whatever-private' }

           expect(response).to be_forbidden # < boom; and response.forbidden? is false
         end
      end
 ```

The exception bubble up from `ruby/gems/3.2.0/gems/super_diff-0.10.0/lib/super_diff/object_inspection/inspection_tree.rb:72` in `insert_hash_inspection_of'.

**Comment by jas14** [comment]
This looks like a duplicate of #163 based on the last stack trace frame, does that seem right @fwolfst ?

**Comment by jas14** [comment]
I was able to reproduce with a very simple app and may have found the culprit: `ActiveSupport::OrderedOptions`. This class [specifically](https://github.com/rails/rails/blob/d0f40f71b0b61f828291f366bad5d29ab44e70d2/activesupport/lib/active_support/ordered_options.rb#L64C9-L66) defines `respond_to_missing?` as `true` for everything. Thus, SuperDiff's `InspectionTreeBuilders::CustomObject` will be mistakenly applied to `OrderedOptions`, which will [call](https://github.com/mcmire/super_diff/blob/fb6718a2b60bc8135424295cc069a4b984983f77/lib/super_diff/object_inspection/inspection_tree_builders/custom_object.rb#L18) `insert_hash_inspection_of(nil)`, which will raise as described.

**Comment by fwolfst** [comment]
Sorry for having been mute. Awesome @jas14 and @mcmire ; thank you.
