### ISSUE TITLE
Less color output + no diff when using super_diff

### ISSUE THREAD

**Issue by blaineventurine** [splitwise/super_diff#207]
First, thanks for your work on this gem! It was indispensable in a previous codebase, and I'd like to get it working with my current situation, but I'm having some trouble. RSpec produces less color output and no diff with `super_diff`:

![Screenshot 2024-01-10 at 10 35 45 AM](https://github.com/mcmire/super_diff/assets/18129692/b601956b-0ad6-4c37-bd51-53d18e2ca1a7)

Here's my normal RSpec output:

![Screenshot 2024-01-10 at 10 36 17 AM](https://github.com/mcmire/super_diff/assets/18129692/782f454c-7a33-4209-9e29-d11d97301ec1)

`super_diff` does show the full hash (no `...` obscuring properties), but it doesn't print it cleanly, there is no color, and there isn't even the key shown.

Ruby: 3.0.1
RSpec: 3.12.2
rspec-rails: 5.1.2
Rails: 6.1.7.6

I've added the default config to the `rails_helper`, and I've tried manually forcing it to show color output, show the key, changing the colors, etc., and I did have it working on a different project that was on the same major versions of Ruby/Rails/RSpec, so I'm kind of at a loss as to why it's not working now. Any ideas? I've even tried basic comparisons, like `expect(q).to eq(2)`.

**Comment by jas14** [comment]
Hey @blaineventurine , sorry for the delay, and thanks for the library versions – that's very helpful.

I'll note first that I don't plan on maintaining compatibility with end-of-life Ruby versions, so 3.0 will be technically unsupported. I'll bump the minimum supported Ruby version in the next release. I'm also assuming you're on `rspec` 3.12.0 and `rspec-core` 3.12.2 (latest in the 3.12.x series is 3.12.3 FWIW).

I can see that the `receive` expectation failure output isn't colored with `super_diff/rspec` included. Is that what you mean? I'm not sure exactly what you're expecting for `expect(q).to eq(2)`, but I can't reproduce the coloring issue.

Do you mind providing:

* a small reproducible spec that doesn't produce what you expect
* if possible, the versions of gems for which it _does_ produce what you expect
* what exactly you expect to happen?

**Comment by blaineventurine** [comment]
Hey @jas14, thanks for getting back to me!

It was the coloring issue that I meant, but in the past 9 months, we have upgraded to Ruby 3.3, along with current versions of all the libraries I mentioned except for Rails. At some point along the way, `super_diff` started working exactly as expected. I'm sorry I can't provide more details.
