### ISSUE TITLE
undefined method error in previously working rspecs

### ISSUE THREAD

**Issue by melancholyfleur** [splitwise/super_diff#228]
In a customized rspec module using SuperDiff, we are getting an error in the new gem version `0.11.0` that extends `SuperDiff::ObjectInspection::InspectionTreeBuilders::Base`. The related code is in a file called `spec/support/super_diff.rb` and it looks like this:
```
class MoneyInspectionTreeBuilder < SuperDiff::ObjectInspection::InspectionTreeBuilders::Base
  def self.applies_to?(value)
    value.is_a?(::Money)
  end

  def call
    SuperDiff::ObjectInspection::InspectionTree.new do
      as_lines_when_rendering_to_lines(collection_bookend: :open) do
        add_text do |object|
          "#<#{object.class.name} \"#{object.format}\""
        end
      end

      when_rendering_to_string do
        add_text " "
      end

      nested do |object|
        as_lines_when_rendering_to_lines do
          add_text do |object|
            "fractional:#{object.fractional}"
          end
        end

        when_rendering_to_string do
          add_text " "
        end

        as_lines_when_rendering_to_lines do
          add_text do |object|
            "currency:#{object.currency.iso_code}"
          end
        end
      end

      as_lines_when_rendering_to_lines(collection_bookend: :close) do
        add_text ">"
      end
    end
  end
end

SuperDiff.configure do |config|
  config.add_extra_inspection_tree_builder_classes(MoneyInspectionTreeBuilder)
end
```

and the error we get now is, as one example:
`undefined method `as_lines_when_rendering_to_lines' for #<MoneyInspectionTreeBuilder:0x00000001144f20a8 @object=#<Money fractional:7800 currency:GBP>>`

Looking at the [changelog](https://github.com/mcmire/super_diff/commit/181b1020a989e4106c62db74618851fa559f40f7#diff-949984e8741356feaeedd08277183bb3f7c94e7b20416002c74a97eacfcd1b63), it seems that there are differences in how that method is used there, but I wasn't sure exactly how to fix our code or if we should use the same structure. I wasn't able to find if that method changed in the new version.

Let me know if I can give anymore information. Thank you!

**Comment by melancholyfleur** [comment]
Found a solution to this. The way Money objects are called changed, so it needs to use all the `t1` and `t2` and `t3` type variables the way it looks in the changelog file.

**Comment by zorab47** [comment]
> Found a solution to this. The way Money objects are called changed, so it needs to use all the `t1` and `t2` and `t3` type variables the way it looks in the changelog file.

FYI, It was the way the `super_diff` interface changed to using block variables instead of instance evals for the inspection trees. Nothing directly related to the `Money` objects.

**Comment by mcmire** [comment]
Hi @melancholyfleur! Sorry that you ran into this issue. I should have marked the change to InspectionTree as breaking in the changelog and offered more information on how to adapt to it. I'm glad you figured it out, but for anyone else stumbling into this, I have new information in the [0.11.0 changelog](https://github.com/mcmire/super_diff/blob/main/CHANGELOG.md#0110---2024-02-10).
