### ISSUE TITLE
I'm no longer maintaining this project, and I am archiving this repo

### ISSUE THREAD

**Issue by mcmire** [splitwise/super_diff#256]
As you may have noticed, my activity on this repo has been rather low for a while now. Due to personal demands, my free time is much more limited these days than it used to be. Additionally, maintaining this project has become more of a burden than a joy. I understand that many people are interested in seeing certain features implemented and bugs fixed, but I'm not able to continue development at this time, and I do not expect to be able to do in the foreseeable future. Rather than leave this repo in an ostensible state of limbo, I am archiving it.

For more on this decision, see [this post on my blog](https://www.elliotwinkler.com/why-im-retiring-from-opensource).

If you're interested in taking this project over, please [email me](mailto:elliot.winkler@gmail.com) (but serious inquiries only, please).

**Comment by gmcquistin** [comment]
Thank you so much for everything you've done. This project has been invaluable for me and lots of others. Wishing you all the best, thanks again 😊

**Comment by jas14** [comment]
Elliot has graciously agreed to pass this project on to us at Splitwise – you can read more [here](https://blog.splitwise.com/2024/09/11/super-diff-plus-splitwise/). Thanks for everything @mcmire !
