### ISSUE TITLE
User's personal `.rspec` file could conflict with the test suite

### ISSUE THREAD

**Issue by Mange** [splitwise/super_diff#60]
[EDIT:] To make it clear, this related to running this project's test suite. In my case because I wanted to contribute patches. This is not something that happens to project *using* this gem.

I have a `~/.rspec` file that contains `--color`. This causes all tests to fail. Putting a `.rspec` file in the repo with either `--no-color` or nothing at all does not fix it.

Removing my `~/.rspec` file causes the tests to work again.

Overriding `$HOME` and `$XDG_CONFIG_HOME` when executing `rspec` seems to work for me, but I wonder if there are any other dangerous effects of this.

```bash
XDG_CONFIG_HOME=/tmp HOME=/tmp SPEC_OPTS="" rspec ./spec/integration/rspec/contain_exactly_matcher_spec.rb:146
```

In theory, one could also refactor the runner so that color enabling isn't just set in the RSpec configuration but is also passed along to the `rspec` command itself. That would be more stable, even though it might still have issues with other things set up in the user's config.

**Comment by mcmire** [comment]
Hey! Sorry for the delay on this. I'm not exactly sure why this is happening, but I was able to reproduce this bug successfully and fix this. Give this branch/PR a shot and see if this fixes the issue for you: https://github.com/mcmire/super_diff/pull/62

**Comment by mcmire** [comment]
Just wanted to check again on this. Did that branch end up working for you?

**Comment by Mange** [comment]
Works for me! :+1: 

Sorry for not getting back to you. I must've missed the first notification.

**Comment by mcmire** [comment]
Sweet! Merging now.
