### ISSUE TITLE
No ActiveRecord causes NameError

### ISSUE THREAD

**Issue by KaptajnKold** [splitwise/super_diff#65]
I have a Rails application which doesn't use ActiveRecord (instead of a database, it connects to a REST API). When I add super_diff and run my test suite, I get lots of examples failing with `uninitialized constant ActiveRecord`

**Comment by mcmire** [comment]
I just merged in #64 which should make it possible to use this gem without ActiveRecord. Try the new v0.4.0 and see if that solves your issue!

**Comment by KaptajnKold** [comment]
The isse is indeed solved :)

**Comment by mcmire** [comment]
Great! :)
