### ISSUE TITLE
Color is not getting completely disabled

### ISSUE THREAD

**Issue by mcmire** [splitwise/super_diff#82]
When disabling color, it seems that it does remove the escape codes from the diff, but not from the "Diff" header or the key.

**Comment by magni-** [comment]
Could this be from this line?
https://github.com/mcmire/super_diff/blob/v0.9.0/lib/super_diff/rspec/monkey_patches.rb#L75

```diff
-            if RSpec.configuration.color_enabled? && code = console_code_for(code_or_symbol)
+            if SuperDiff.configuration.color_enabled? && code = console_code_for(code_or_symbol)
```

**Comment by mcmire** [comment]
Yeah, we'd want to confirm in a test, but I think that may be it.
