### ISSUE TITLE
Release version compatible with Ruby 2.7

### ISSUE THREAD

**Issue by imanel** [splitwise/super_diff#89]
We're currently using master, as [it has changes bringing 2.7 compatibility](https://github.com/mcmire/super_diff/compare/v0.4.2...master), however since it looks stable it could be useful to release new changes as next version. Are there any plans for it?

**Comment by mcmire** [comment]
Hey @imanel! Sorry for the wait. Usually I release pretty quickly, but I've been busy working on a new feature to handle #75. I should have this ready within the next week or two, though, and then I'll release a new version after that.

**Comment by aried3r** [comment]
Hey @mcmire, I know you've already said when this fix is going to land, but I was wondering if we could get a small release before #75? No real reason except that the deprecation warnings are a minor inconvenience in our CI logs.

Appreciate your work on this gem!

**Comment by mcmire** [comment]
@aried3r Ah, ok, good point! v0.5.0 is now available (release notes [here](https://github.com/mcmire/super_diff/blob/v0.5.0/CHANGELOG.md#050---2020-06-18)).

**Comment by aried3r** [comment]
Thank you, I appreciate it!
